name: Email Step

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: 24f3000312@ds.study.iitm.ac.in
        run: echo "Hello, world!"
