name: Email Step Example

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 24f3000312@ds.study.iitm.ac.in
        run: echo "Hello, world!"
